```{r}
#label:setup
library(tidyverse)
library(lubridate)
library(sf)
library(here)
library(tmap)
library(sp)
library(spdep)
library(spatialreg)
library(lmtest)
library(sandwich)
library(units)
library(car)
library(foreign)
library(tigris)
library(tidycensus)
library(gt)
library(flextable)
library(modelsummary)
library(tidycensus)
```

```{r}
lc_ejscreen_map <- read_sf("./Data/EJ_Screen_2015_LucasCountyOH.gpkg")
```


```{r}
# Foreslår at dere kaller kartet som inneholder dataene for lc_ejscreen_map
lc_ejscreen_map <- lc_ejscreen_map |> 
  select(
    ID, # Census FIPS code for block group
    
    # Nabolagsvariabler
    LINGISOPCT, # % of households (interpreted as individuals) in linguistic isolation
    LOWINCPCT, # % low-income
    LESSHSPCT, # % less than high school
    OVER64PCT, # % over age 64
    VULEOPCT, # Demographic Index (based on 2 factors, % low-income and % minority)
    
    # Miljøvariabler
    PRE1960PCT, # % pre-1960 housing (lead paint indicator)
    PTRAF, # % Traffic proximity and volume
    PWDIS, # Proximity to major direct dischargers to water
    PNPL, # Proximity to National Priorities List (NPL) sites
    PRMP, # Proximity to Risk Management Plan (RMP) facilities
    PTSDF, # Proximity to Treatment Storage and Disposal (TSDF) facilities
    OZONE, # Ozone level in air
    PM25 # PM2.5 level in air
  )
```


```{r}
census_api_key("2b1d7cb91812dfd520e7ddd57f4d15506669735c", install = TRUE)
# Reload .Renviron
readRenviron("~/.Renviron")
```

### Boligdata

```{r}
data(house, package = "spData")

lucas_house <- house |>
  st_as_sf() |>
  st_transform(2834)


lucas_house <- lucas_house |>
  mutate(
    sale_date = ymd(sdate),
    year_month = factor(format(sale_date, "%Y-%m"))
  )

range(lucas_house$sale_date)
nlevels(lucas_house$year_month)
```


### Per Capita Income

```{r}
acs5_income <- 
  get_acs(
    geography = "tract",
    variables = c("B19301_001"),
    state = "OH",
    county = "Lucas County",
    year = 2011,
    survey = "acs5",
    geometry = TRUE
  )
```

### Race

### Travel Time to Work

### Median Household Income

### Employment Status

### Ratio of Income to Poverty Level

### Merging data to full set
